# This will be where the specific files for each service are mapped out.
# SERVICE:
#   ENVIRONMENT:
#       - array of paths
---
challenge: 
  test:
    - exponent.cpp

oauth:
  admin:
    - config/path/to/test/oauth.yml
    - config/path/to/test/oauth2.yml
    - config/path/to/test/oauth3.yml
    - config/path/to/test/oauth4.yml
  test:
    - config/path/to/prod/oauth.yml
    - config/path/to/prod/oauth2.yml
    - config/path/to/prod/oauth3.yml
    - config/path/to/prod/oauth4.yml

crypto:
  test:
    - config/path/to/test/admin.yml
    - config/path/to/test/admin2.yml
    - config/path/to/test/admin3.yml
    - config/path/to/test/admin4.yml
  production:
    - config/path/to/prod/admin.yml
    - config/path/to/prod/admin2.yml
    - config/path/to/prod/admin3.yml
    - config/path/to/prod/admin4.yml 