service: oauth
environment: null
config_path:
  license:
replacement_term: null
transform: yq -i '(.images[] | select(. == ".registry/env(SERVICE)").newTag) = "env(REPLACE)"'
config_repo_url: https://github.com/Jmfwolf/rehelp.git
